package slf.xbb.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import slf.xbb.domain.ItemStockLogDo;
import slf.xbb.domain.ItemStockLogDoExample;

public interface ItemStockLogDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock_log
     *
     * @mbg.generated Thu May 28 15:42:35 CST 2020
     */
    long countByExample(ItemStockLogDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock_log
     *
     * @mbg.generated Thu May 28 15:42:35 CST 2020
     */
    int deleteByExample(ItemStockLogDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock_log
     *
     * @mbg.generated Thu May 28 15:42:35 CST 2020
     */
    int deleteByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock_log
     *
     * @mbg.generated Thu May 28 15:42:35 CST 2020
     */
    int insert(ItemStockLogDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock_log
     *
     * @mbg.generated Thu May 28 15:42:35 CST 2020
     */
    int insertSelective(ItemStockLogDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock_log
     *
     * @mbg.generated Thu May 28 15:42:35 CST 2020
     */
    List<ItemStockLogDo> selectByExample(ItemStockLogDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock_log
     *
     * @mbg.generated Thu May 28 15:42:35 CST 2020
     */
    ItemStockLogDo selectByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock_log
     *
     * @mbg.generated Thu May 28 15:42:35 CST 2020
     */
    int updateByExampleSelective(@Param("record") ItemStockLogDo record, @Param("example") ItemStockLogDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock_log
     *
     * @mbg.generated Thu May 28 15:42:35 CST 2020
     */
    int updateByExample(@Param("record") ItemStockLogDo record, @Param("example") ItemStockLogDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock_log
     *
     * @mbg.generated Thu May 28 15:42:35 CST 2020
     */
    int updateByPrimaryKeySelective(ItemStockLogDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock_log
     *
     * @mbg.generated Thu May 28 15:42:35 CST 2020
     */
    int updateByPrimaryKey(ItemStockLogDo record);
}