package slf.xbb.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import slf.xbb.domain.OrderDo;
import slf.xbb.domain.OrderDoExample;

public interface OrderDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Apr 04 07:35:10 CST 2020
     */
    long countByExample(OrderDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Apr 04 07:35:10 CST 2020
     */
    int deleteByExample(OrderDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Apr 04 07:35:10 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Apr 04 07:35:10 CST 2020
     */
    int insert(OrderDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Apr 04 07:35:10 CST 2020
     */
    int insertSelective(OrderDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Apr 04 07:35:10 CST 2020
     */
    List<OrderDo> selectByExample(OrderDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Apr 04 07:35:10 CST 2020
     */
    OrderDo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Apr 04 07:35:10 CST 2020
     */
    int updateByExampleSelective(@Param("record") OrderDo record, @Param("example") OrderDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Apr 04 07:35:10 CST 2020
     */
    int updateByExample(@Param("record") OrderDo record, @Param("example") OrderDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Apr 04 07:35:10 CST 2020
     */
    int updateByPrimaryKeySelective(OrderDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Apr 04 07:35:10 CST 2020
     */
    int updateByPrimaryKey(OrderDo record);
}