package slf.xbb.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import slf.xbb.domain.PromoDo;
import slf.xbb.domain.PromoDoExample;

public interface PromoDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Apr 05 09:40:22 CST 2020
     */
    long countByExample(PromoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Apr 05 09:40:22 CST 2020
     */
    int deleteByExample(PromoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Apr 05 09:40:22 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Apr 05 09:40:22 CST 2020
     */
    int insert(PromoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Apr 05 09:40:22 CST 2020
     */
    int insertSelective(PromoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Apr 05 09:40:22 CST 2020
     */
    List<PromoDo> selectByExample(PromoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Apr 05 09:40:22 CST 2020
     */
    PromoDo selectByPrimaryKey(Integer id);

    /**
     *
     * @param itemId
     * @return
     */
    PromoDo selectByItemId(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Apr 05 09:40:22 CST 2020
     */
    int updateByExampleSelective(@Param("record") PromoDo record, @Param("example") PromoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Apr 05 09:40:22 CST 2020
     */
    int updateByExample(@Param("record") PromoDo record, @Param("example") PromoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Apr 05 09:40:22 CST 2020
     */
    int updateByPrimaryKeySelective(PromoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Apr 05 09:40:22 CST 2020
     */
    int updateByPrimaryKey(PromoDo record);
}