package slf.xbb.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import slf.xbb.domain.SequenceDo;
import slf.xbb.domain.SequenceDoExample;

public interface SequenceDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Apr 04 23:03:58 CST 2020
     */
    long countByExample(SequenceDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Apr 04 23:03:58 CST 2020
     */
    int deleteByExample(SequenceDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Apr 04 23:03:58 CST 2020
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Apr 04 23:03:58 CST 2020
     */
    int insert(SequenceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Apr 04 23:03:58 CST 2020
     */
    int insertSelective(SequenceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Apr 04 23:03:58 CST 2020
     */
    List<SequenceDo> selectByExample(SequenceDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Apr 04 23:03:58 CST 2020
     */
    SequenceDo selectByPrimaryKey(String name);

    /**
     * 此方法和selectByPrimaryKey类似，但是使用了for update锁行
     * @param name
     * @return
     */
    SequenceDo getSequenceByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Apr 04 23:03:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") SequenceDo record, @Param("example") SequenceDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Apr 04 23:03:58 CST 2020
     */
    int updateByExample(@Param("record") SequenceDo record, @Param("example") SequenceDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Apr 04 23:03:58 CST 2020
     */
    int updateByPrimaryKeySelective(SequenceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Apr 04 23:03:58 CST 2020
     */
    int updateByPrimaryKey(SequenceDo record);
}