package slf.xbb.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import slf.xbb.domain.UserPasswordDo;
import slf.xbb.domain.UserPasswordDoExample;

public interface UserPasswordDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Apr 02 09:42:15 CST 2020
     */
    long countByExample(UserPasswordDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Apr 02 09:42:15 CST 2020
     */
    int deleteByExample(UserPasswordDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Apr 02 09:42:15 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Apr 02 09:42:15 CST 2020
     */
    int insert(UserPasswordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Apr 02 09:42:15 CST 2020
     */
    int insertSelective(UserPasswordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Apr 02 09:42:15 CST 2020
     */
    List<UserPasswordDo> selectByExample(UserPasswordDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Apr 02 09:42:15 CST 2020
     */
    UserPasswordDo selectByPrimaryKey(Integer id);

    /**
     * 
     * @param id
     * @return
     */
    UserPasswordDo selectByUserId(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Apr 02 09:42:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserPasswordDo record, @Param("example") UserPasswordDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Apr 02 09:42:15 CST 2020
     */
    int updateByExample(@Param("record") UserPasswordDo record, @Param("example") UserPasswordDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Apr 02 09:42:15 CST 2020
     */
    int updateByPrimaryKeySelective(UserPasswordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Apr 02 09:42:15 CST 2020
     */
    int updateByPrimaryKey(UserPasswordDo record);
}