server:
  port: 80
  tomcat:
      accept-count: 1000
      max-threads: 800
      min-spare-threads: 100
      accesslog:
        enabled: true
        pattern: "%t [%I] %{X-Forwarded-For}i %l %u %r %s %b %D"
        directory: ./tomcatlog
spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://123.57.204.209/seckill?useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver‐class‐name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 123.57.204.209
    port: 6379
    database: 10
    jedis:
      pool:
        max-active: 50
        min-idle: 20